CREATE TABLE STUDENTS(
STID INT,
STUDENTNAME VARCHAR(50),
CITY VARCHAR(50),
MARKS INT,
RESULT VARCHAR(50),
);
INSERT INTO STUDENTS(STID,STUDENTNAME,CITY,MARKS,RESULT) VALUES (1,'rahul','chennai',950,'1st');
INSERT INTO STUDENTS(STID,STUDENTNAME,CITY,MARKS,RESULT) VALUES (2,'ramya','tirupati',700,'3nd');
INSERT INTO STUDENTS(STID,STUDENTNAME,CITY,MARKS,RESULT) VALUES (3,'sony','kadapa',650,'3nd');
INSERT INTO STUDENTS(STID,STUDENTNAME,CITY,MARKS,RESULT) VALUES (4,'vijay','kadapa',550,'4nd');
INSERT INTO STUDENTS(STID,STUDENTNAME,CITY,MARKS,RESULT) VALUES (5,'keerthi','chittor',345,'fail');
SELECT DISTINCT * FROM STUDENTS ;
SELECT STID,STUDENTNAME,MARKS,MARKS+10 FROM STUDENTS;
SELECT STID,STUDENTNAME,MARKS,MARKS+10 AS "MODIFIED MARKS" FROM STUDENTS;

