CREATE TABLE CUSTOMERS(
  ID INT NOT NULL,
  NAME VARCHAR(30) NOT NULL,
  ADDRESS CHAR (25),
  SALARY DECIMAL(18,2),
  PRIMARY KEY(ID)
  );
  ALTER TABLE CUSTOMERS ADD AGE INT NOT NULL;
  SELECT *FROM CUSTOMERS ;
  INSERT INTO CUSTOMERS( ID,NAME,ADDRESS, SALARY, AGE) VALUES(1,'Hardik','delhi',10000.00,32);
  INSERT INTO CUSTOMERS( ID,NAME,ADDRESS, SALARY, AGE) VALUES(2,'lilly','hyderabad',8200.00,28);
  INSERT INTO CUSTOMERS( ID,NAME,ADDRESS, SALARY, AGE) VALUES(3,'muffy','mumbai',12000.00,25);
  INSERT INTO CUSTOMERS( ID,NAME,ADDRESS, SALARY, AGE) VALUES(4,'lucky','bhopal',6500.00,26);
  INSERT INTO CUSTOMERS( ID,NAME,ADDRESS, SALARY, AGE) VALUES(5,'lissy','hyderabad',7500.00,26);
  INSERT INTO CUSTOMERS( ID,NAME,ADDRESS, SALARY, AGE) VALUES(6,'rakesh','kolkata',5500.00,30);

  SELECT *FROM CUSTOMERS ;
  SELECT COUNT(ID), ADDRESS FROM CUSTOMERS GROUP BY ADDRESS HAVING COUNT(ID) > 1 ;
  SELECT COUNT(ID) as customer_count from CUSTOMERS ;
  INSERT INTO CUSTOMERS( ID,NAME,ADDRESS, SALARY, AGE) VALUES(7,'ricky','bhopal',10500.00,26);
  INSERT INTO CUSTOMERS( ID,NAME,ADDRESS, SALARY, AGE) VALUES(8,'disha','kolkata',24000.00,30);
  ALTER TABLE CUSTOMERS DROP COLUMN SALARY;
  begin tran;
  DELETE FROM CUSTOMERS WHERE NAME='ricky' and AGE=26;
  commit;
  begin tran;
  DELETE FROM CUSTOMERS WHERE NAME='lissy' and AGE=26;
  rollback;
  begin tran;
  save tran s1;
  DELETE FROM CUSTOMERS WHERE NAME='lissy' and AGE=26;
  begin tran;
  DELETE FROM CUSTOMERS WHERE NAME='muffy' and AGE=25;
  save tran s2;
  begin tran;
  DELETE FROM CUSTOMERS WHERE NAME='disha' and AGE=30;
  save tran s3;
  rollback tran s2;
  
  SELECT * FROM CUSTOMERS WHERE NAME LIKE '%a';
  SELECT * FROM CUSTOMERS WHERE NAME LIKE '%y';
  SELECT * FROM CUSTOMERS WHERE address IN ('hyderabad','bhopal','kolkata');
  SELECT * FROM CUSTOMERS WHERE AGE BETWEEN 25 AND 30;
  ALTER TABLE CUSTOMERS ADD EMAILID varchar(255);

  CREATE TABLE CUSTOMERS2 ( 
  ID INT NOT NULL,
  NAME VARCHAR(30) NOT NULL,
  ADDRESS CHAR (25),
  AGE INT,
  EMAILID VARCHAR(255),
  PRIMARY KEY(ID)
  );
 INSERT INTO CUSTOMERS2( ID,NAME,ADDRESS, AGE,EMAILID) VALUES(9,'viswa','kadapa',25,'viswa123@gmail.com');
  INSERT INTO CUSTOMERS2( ID,NAME,ADDRESS, AGE,EMAILID) VALUES(10,'lilly','hyderabad',28,'lillybaby@gmail.com');
  INSERT INTO CUSTOMERS2( ID,NAME,ADDRESS, AGE,EMAILID) VALUES(11,'muffy','tirupati',25,'muffy423@gmail.com');
  INSERT INTO CUSTOMERS2( ID,NAME,ADDRESS, AGE,EMAILID) VALUES(12,'lucky','bhopal',26,'luckyroy@gmail.com');
  DELETE FROM CUSTOMERS WHERE NAME= 'muffy' ;
  

  
  CREATE TABLE CUSTOMERS3 ( 
  ID INT NOT NULL,
  NAME VARCHAR(30) NOT NULL,
  ADDRESS CHAR (25),
  AGE INT,
  EMAILID VARCHAR(255),
  PRIMARY KEY(ID)
  );
  
  INSERT INTO CUSTOMERS3( ID,NAME,ADDRESS, AGE,EMAILID) VALUES(11,'kalyan','kadapa',24,'KALYAN123@gmail.com');
  INSERT INTO CUSTOMERS3( ID,NAME,ADDRESS, AGE,EMAILID) VALUES(12,'rupa','hyderabad',22,'rupababy@gmail.com');
  SELECT *FROM CUSTOMERS3 ;
  SELECT *FROM CUSTOMERS UNION SELECT *FROM CUSTOMERS3 ;

