CREATE TABLE EMP_HYD(EID INT,ENAME VARCHAR(50),SALARY MONEY)
CREATE TABLE EMP_CHENNAI(EID INT,ENAME VARCHAR(50),SALARY MONEY)
SELECT* FROM EMP_HYD;
TRUNCATE TABLE EMP_HYD ;
INSERT INTO EMP_HYD VALUES(101,'ADAMS',85000),(102,'SCOTT',34000),(103,'JAMES',55000),(104,'WARNER',12000);
INSERT INTO EMP_CHENNAI VALUES(101,'ADAMS',85000),(105,'ALLEN',11000),(106,'MILLER',98000);
SELECT* FROM EMP_CHENNAI;
SELECT* FROM EMP_HYD UNION SELECT* FROM EMP_CHENNAI;
SELECT* FROM EMP_HYD UNION ALL SELECT* FROM EMP_CHENNAI;
SELECT* FROM EMP_HYD INTERSECT SELECT* FROM EMP_CHENNAI;
SELECT* FROM EMP_HYD EXCEPT SELECT* FROM EMP_CHENNAI;
---------------PRIMARY KEY----------
 CREATE TABLE DEPARTMENT(DEPTNO INT PRIMARY KEY,DNAME VARCHAR(40),LOCATION VARCHAR(40))
 INSERT INTO DEPARTMENT VALUES(10,'DBA','HYD'),(20,'SAP','MUMBAI'),(30,'HR','PUNE');
 ------------FOREIGNKEY-------------
 CREATE TABLE EMPLOYEE(EMPID INT,ENAME VARCHAR(50),SALARY MONEY,DEPTNO INT FOREIGN KEY REFERENCES DEPARTMENT(DEPTNO))

 INSERT INTO EMPLOYEE VALUES(101,'ADAMS',85000,10),(102,'JAMES',45000,20),(103,'SCOTT',23000,30);
 SELECT*FROM DEPARTMENT;
 SELECT*FROM EMPLOYEE;
 CREATE TABLE STUDENT(STID INT,SNAME VARCHAR(50),SMAILID VARCHAR(50),COURSEID INT)
 INSERT INTO STUDENT VALUES(101,'ADAMS','add@gmail.com',10),
 (102,'JAMES','jay@hotmail.com',20),(103,'SCOTT','scot@yahoo.com',30);
 CREATE TABLE COURSE(STID INT,CNAME VARCHAR(50),CFEE DECIMAL(6,2))
 INSERT INTO COURSE VALUES(10,'SQL SERVER',1200),(20,'SQLDBA',1500),(30,'MSBI',3200),(40,'SAP',2400);
 SELECT*FROM COURSE;
 UPDATE COURSE SET STID=40 WHERE STID=30;
  UPDATE COURSE SET STID=50 WHERE STID=40;
 DELETE COURSE WHERE STID=50;
 INSERT INTO COURSE VALUES(40,'MSBI',3200),(50,'SAP',2400);
 SELECT*FROM STUDENT;
 SELECT*FROM COURSE;
 insert into course values(60,'MYSQL',1200);
 EXEC SP_RENAME 'COURSE.STID', 'COURSEID', 'COLUMN'
 SELECT* FROM STUDENT INNER JOIN COURSE ON STUDENT.COURSEID=COURSE.COURSEID;
 SELECT* FROM STUDENT LEFT OUTER JOIN COURSE ON STUDENT.COURSEID=COURSE.COURSEID;
 SELECT* FROM STUDENT RIGHT OUTER JOIN COURSE ON STUDENT.COURSEID=COURSE.COURSEID;
 SELECT* FROM STUDENT FULL OUTER JOIN COURSE ON STUDENT.COURSEID=COURSE.COURSEID;

 ----3*4------
 SELECT* FROM STUDENT CROSS JOIN COURSE 
 ----SELF JOIN----
 SELECT C1.COURSEID,C1.CNAME,C1.CFEE FROM COURSE C1,COURSE C2 WHERE C1.CFEE=C2.CFEE
 AND C2.CNAME='MYSQL';/* WE HAVE TO USE ANOTHER ALIASNAME TO GET RESULT*/
 ----UNIQUE------
 CREATE TABLE TEST1(SNO INT UNIQUE,LOCATION VARCHAR(50) UNIQUE)
 INSERT TEST1 VALUES(101,'HYD')
  INSERT TEST1 VALUES(102,'DELHI')
   INSERT TEST1 VALUES(NULL,'NULL')
   SELECT*FROM TEST1;
   -------NOTNULL-----
   CREATE TABLE TEST2(SNO INT NOT NULL,LOCATION VARCHAR(50) NOT NULL)
 INSERT TEST2 VALUES(101,'AA')
  INSERT TEST2 VALUES(101,'AA')
   INSERT TEST2 VALUES(NULL,'AA')
   ----CHECK---
   CREATE TABLE TEST3(SNO INT,SAL MONEY CHECK(SAL>=5000))
 INSERT TEST3 VALUES(1,4999)
  INSERT TEST3 VALUES(1,5000)
  --------------